export  const rentalData = {
  2024: {
    simple: [
      { month: "Jan", count: 12 },
      { month: "Feb", count: 8 },
      { month: "Mar", count: 15 },
      { month: "Apr", count: 10 },
      { month: "May", count: 20 },
      { month: "Jun", count: 18 },
      { month: "Jul", count: 25 },
      { month: "Aug", count: 22 },
      { month: "Sep", count: 14 },
      { month: "Oct", count: 17 },
      { month: "Nov", count: 9 },
      { month: "Dec", count: 11 },
    ],
    Rugged: [
      { month: "Jan", count: 5 },
      { month: "Feb", count: 7 },
      { month: "Mar", count: 6 },
      { month: "Apr", count: 9 },
      { month: "May", count: 14 },
      { month: "Jun", count: 18 },
      { month: "Jul", count: 21 },
      { month: "Aug", count: 19 },
      { month: "Sep", count: 12 },
      { month: "Oct", count: 15 },
      { month: "Nov", count: 8 },
      { month: "Dec", count: 10 },
    ],
    luxury: [
      { month: "Jan", count: 2 },
      { month: "Feb", count: 3 },
      { month: "Mar", count: 4 },
      { month: "Apr", count: 5 },
      { month: "May", count: 7 },
      { month: "Jun", count: 10 },
      { month: "Jul", count: 12 },
      { month: "Aug", count: 14 },
      { month: "Sep", count: 8 },
      { month: "Oct", count: 6 },
      { month: "Nov", count: 4 },
      { month: "Dec", count: 5 },
    ],
  },
    2023: {
    simple: [
      { month: "Jan", count: 60 },
      { month: "Feb", count: 8 },
      { month: "Mar", count: 15 },
      { month: "Apr", count: 10 },
      { month: "May", count: 20 },
      { month: "Jun", count: 18 },
      { month: "Jul", count: 2 },
      { month: "Aug", count: 30 },
      { month: "Sep", count: 14 },
      { month: "Oct", count: 17 },
      { month: "Nov", count: 9 },
      { month: "Dec", count: 11 },
    ],
    Rugged: [
      { month: "Jan", count: 5 },
      { month: "Feb", count: 7 },
      { month: "Mar", count: 6 },
      { month: "Apr", count: 12 },
      { month: "May", count: 7 },
      { month: "Jun", count: 18 },
      { month: "Jul", count: 45 },
      { month: "Aug", count: 19 },
      { month: "Sep", count: 12 },
      { month: "Oct", count: 15 },
      { month: "Nov", count: 8 },
      { month: "Dec", count: 10 },
    ],
    luxury: [
      { month: "Jan", count: 2 },
      { month: "Feb", count: 3 },
      { month: "Mar", count: 4 },
      { month: "Apr", count: 5 },
      { month: "May", count: 70 },
      { month: "Jun", count: 10 },
      { month: "Jul", count: 23 },
      { month: "Aug", count: 14 },
      { month: "Sep", count: 8 },
      { month: "Oct", count: 6 },
      { month: "Nov", count: 12 },
      { month: "Dec", count: 5 },
    ],
  }
  
};